Teste teams

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -37,6 +37,17 @@ jobs:
         env:
           CI: true
 
+      - name: Validate Cypress test results
+        if: failure()
+        run: |
+          test_results=$(npm run teste)
+          if [[ $test_results == *"All tests passed"* ]]; then
+            echo "All tests passed. Continuing with the workflow."
+          else
+            echo "Some tests failed. Aborting the workflow."
+            exit 1
+          fi
+
       - name: Archive test results
         if: failure()
         uses: actions/upload-artifact@v2
@@ -54,30 +65,30 @@ jobs:
       - name: Send notification to Microsoft Teams
         if: failure()
         run: |
-            WEBHOOK_URL="https://mkmservicecom.webhook.office.com/webhookb2/a11da518-494e-4b92-ab2e-eae01ec8ff11@6bb1f81b-c7c7-4eec-a417-11ceb617097d/IncomingWebhook/73006ad307184662bfbe7b39dec2a5f3/6707798e-6692-4adb-8ec0-09ea01b9bb94"
-            curl -X POST -H "Content-Type: application/json" -d '{
-              "@type": "MessageCard",
-              "@context": "http://schema.org/extensions",
-              "summary": "Cypress Test Results",
-              "themeColor": "FF0000",
-              "sections": [{
-                "activityTitle": "Cypress Test Suite Failed",
-                "activitySubtitle": "A test run has failed",
-                "facts": [{
-                  "name": "Repository",
-                  "value": "${{ github.repository }}"
-                  }, 
-                  {
-                  "name": "Error Details",
-                  "value": "'$ERROR_LOG'"
-                  } ,{
-                  "name": "Branch",
-                  "value": "${{ github.ref }}"
-                }, {
-                  "name": "Commit",
-                  "value": "${{ github.sha }}"
-                }],
-                "markdown": true
-              }]
-            }' "$WEBHOOK_URL"
-        
+          WEBHOOK_URL="https://mkmservicecom.webhook.office.com/webhookb2/a11da518-494e-4b92-ab2e-eae01ec8ff11@6bb1f81b-c7c7-4eec-a417-11ceb617097d/IncomingWebhook/73006ad307184662bfbe7b39dec2a5f3/6707798e-6692-4adb-8ec0-09ea01b9bb94"
+          ERROR_LOG=$(cat /path/to/error.log)  # Coloque o caminho real do arquivo de log de erro
+          curl -X POST -H "Content-Type: application/json" -d '{
+            "@type": "MessageCard",
+            "@context": "http://schema.org/extensions",
+            "summary": "Cypress Test Results",
+            "themeColor": "FF0000",
+            "sections": [{
+              "activityTitle": "Cypress Test Suite Failed",
+              "activitySubtitle": "A test run has failed",
+              "facts": [{
+                "name": "Repository",
+                "value": "${{ github.repository }}"
+                }, 
+                {
+                "name": "Error Details",
+                "value": "'$ERROR_LOG'"
+                } ,{
+                "name": "Branch",
+                "value": "${{ github.ref }}"
+              }, {
+                "name": "Commit",
+                "value": "${{ github.sha }}"
+              }],
+              "markdown": true
+            }]
+          }' "$WEBHOOK_URL"
